### PR TITLE
✨ Add icons, slate colour scheme and new user

### PR DESCRIPTION
**Pull request by srisco**
Hi! I love Congo, I'm using it in my [personal website](https://srisco.dev) and I want to contribute by adding some icons I needed and a simple "Full" cool-gray color scheme. I also added my website to users.md.

Thanks for your work!

### CODE REVIEW

**Comment by jpanther** [comment]
Hey @srisco, thanks for your contributions. I have no problem with incorporating these changes. My only comment is that it would be fun to have a name for the colour scheme. Perhaps it could be something like "slate" or "muted"? I'd like to avoid using the word "gray" in the name because it's a very US-centric spelling.

**Comment by srisco** [comment]
Hi, @jpanther "slate" LGTM. I can change the file name and update the docs referencing the new color theme if you want.

Cheers.

**Comment by jpanther** [comment]
Thanks, that would be great if you could. Once that's done I'll merge it in.

**Comment by jpanther** [comment]
Thanks for the changes. I'll merge these in and they'll be included in the next release.

**Pull request merged**
