### PR TITLE
docs: :notebook: add sfz.dev to exampleSite/content/users.md

### PR DESCRIPTION
**Pull request by shin-sforzando**
Hi @jpanther

Thank you for all your great themes.
I have created a website for my company using Congo.
I would be happy if you could add it to the use case.

2022-08-09 01 42 31 sfz dev 8d4063d3fcf6
IMG_A8CD90C669D7-1

My challenges in creating this website are as follows.

- Made the switching between the normal menu and the hamburger menu responsive.
- Added a shortcode for images to spread across the full width of the site.
- Made some design tweaks related to switching between Japanese and English.
- Used [Vanta.js](https://www.vantajs.com) for the background.
- Embedded maps using [Mapbox](https://www.mapbox.com).
- Added thumbnail display to list.html.

I would like to continue to support you. Best regards.

### CODE REVIEW

**Comment by jpanther** [comment]
Thanks for using Congo, @shin-sforzando! I really like what you've achieved with the theme. It looks great! I'll merge this change in and your site will be added to the public list when the next theme release is published.

**Comment by AntoineSoetewey** [comment]
Dear @shin-sforzando,

Great website! Is the repository public?

I really like these two points:
1. Made the switching between the normal menu and the hamburger menu responsive.
2. Made some design tweaks related to switching between Japanese and English.

And if you don't mind I'd like to implement these two points on my websites (in particular the first one, unless @jpanther you want to use this PR to update the template?).

Best,
Antoine

**Comment by shin-sforzando** [comment]
Hi @AntoineSoetewey ,

Yes, it's public.
https://github.com/sforzando/sfz.dev/

As you can see, I've achieved the responsive menu with minimal changes in partial system.

https://github.com/sforzando/sfz.dev/tree/main/layouts/partials/header

This is all thanks to @jpanther 's great theme.

**Comment by jpanther** [comment]
I would like to add the responsive menu in to the base theme. Do you mind if I use your implementation, @shin-sforzando? If you'd like to submit it as your own PR, I'm also open to that.

**Comment by shin-sforzando** [comment]
@jpanther Of course! However, I am not very good with CSS, so I may be implementing it incorrectly. It would be great if you could refine it.

**Pull request merged**
