### PR TITLE
feat: move author field to languages.xx.toml under params

### LINKED ISSUE #690: Hugo v0.120.0 deprecates the author key in site configuration
### Issue description

`site.Author` is deprecated in Hugo v0.120.0 and needs to be migrated to `params.author`

### Theme version

v2.7.2

### Hugo version

v0.120.1

### Which browser rendering engines are you seeing the problem on?

_No response_

### URL to sample repository or website

_No response_

### Hugo output or build error messages

```bash
WARN  The author key in site configuration is deprecated. Use params.author.name instead.
```

### PR DESCRIPTION
**Pull request by Jh123x**
First time contributing so please do let me know if I am doing something wrong.

- [x] feat: move `author` field to `params.toml`
- [x] feat: add warning when `author` field is in `languages.xx.toml` instead of `params.toml`
- [x] docs: update docs to reflect change

Closes #690

### CODE REVIEW

**Comment by Jh123x** [comment]
Not sure how to change the docs correctly.
Do I need to change them for every translation?


For snippets like this in `getting-started`

```toml
# config/_default/languages.en.toml

title = "My awesome website"

[author]
name = "My name"
image = "img/author.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
  { twitter = "https://twitter.com/username" }
]
```

So I just make another snippet that points is something like

```toml
# config/_default/languages.en.toml

title = "My awesome website"
```

```toml
# config/_default/params.toml

[author]
name = "My name"
image = "img/author.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
  { twitter = "https://twitter.com/username" }
]
```

**Comment by jpanther** [comment]
I think this is on the right track, but I don't think moving the author params to `params.toml` is the correct solution as it will be difficult to localise. I have a feeling these need to move under the `[params]` block in the respective `languages.[lang].toml` file.

ie. we end up with:
```toml
[params.author]
name = "Name"
```

I haven't tackled this one yet as it's a bit of breaking change for users to migrate these values and so it needs a minor version bump. It might be valuable to test some fallback scenarios to determine if it can handle using both the values in the correct location and the old location. I also think this change could be bundled into a wider feature that implements multi-author functionality.

**Comment by Jh123x** [comment]
> I think this is on the right track, but I don't think moving the author params to `params.toml` is the correct solution as it will be difficult to localise. I have a feeling these need to move under the `[params]` block in the respective `languages.[lang].toml` file.
> 
> ie. we end up with:
> 
> ```toml
> [params.author]
> name = "Name"
> ```
> 
> I haven't tackled this one yet as it's a bit of breaking change for users to migrate these values and so it needs a minor version bump. It might be valuable to test some fallback scenarios to determine if it can handle using both the values in the correct location and the old location. I also think this change could be bundled into a wider feature that implements multi-author functionality.

Updated! Is the current implementation ok?

**Comment by jpanther** [comment]
That's much better, I think the only thing left to tweak is the warning message. It's directing people to the `params.toml` file when really it should just say that the `author` block needs to be changed to `params.author` in `languages.xx.toml`.

**Comment by jpanther** [comment]
Thanks, looks good. I'll merge it in later today.

**Comment by kelset** [comment]
hey @jpanther - thanks for maintaining this great theme! QQ: am I wrong or this fix hasn't made it yet in a released version? Sorry, I'm not sure familar with the whole Go ecosystem

**Comment by Jh123x** [comment]
> hey @jpanther - thanks for maintaining this great theme! QQ: am I wrong or this fix hasn't made it yet in a released version? Sorry, I'm not sure familar with the whole Go ecosystem

I think it is just in dev and not in a release yet

**Comment by rshmhrj** [comment]
Just upgraded to latest stable 5c8ab32 and `[params.author]` doesn't seem to work for the links section.

image

Adding links under `[author]` displays them,

image

but then the console displays the Congo warning: 

image

Same thing with the `params.author.image` -- doesn't seem to display, so also added it to `author.image`

**Pull request merged**
